//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 02:27:23 PM CEST 
//


package com.csf.documentgeneratorservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;

import org.w3._2005._05.xmlmime.Base64Binary;


/**
 * <p>Java class for tDocumentGenerationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDocumentGenerationRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DsgnNme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OtptTyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtptNme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PublDir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MsgId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UsrNme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InptData" type="{http://www.w3.org/2005/05/xmlmime}base64Binary" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenerateDocumentRequest", propOrder = {
    "dsgnNme",
    "otptTyp",
    "otptNme",
    "publDir",
    "msgId",
    "usrNme",
    "inptData"
})
@XmlRootElement(name = "GenerateDocumentRequest")
public class DocumentGenerationRequest {

    @XmlElement(name = "DsgnNme", required = true)
    protected String dsgnNme;
    @XmlElement(name = "OtptTyp")
    protected String otptTyp;
    @XmlElement(name = "OtptNme")
    protected String otptNme;
    @XmlElement(name = "PublDir")
    protected String publDir;
    @XmlElement(name = "MsgId")
    protected String msgId;
    @XmlElement(name = "UsrNme")
    protected String usrNme;
    @XmlElement(name = "InptData", required = true)
    protected List<Base64Binary> inptData;

    /**
     * Gets the value of the dsgnNme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsgnNme() {
        return dsgnNme;
    }

    /**
     * Sets the value of the dsgnNme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsgnNme(String value) {
        this.dsgnNme = value;
    }

    /**
     * Gets the value of the otptTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtptTyp() {
        return otptTyp;
    }

    /**
     * Sets the value of the otptTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtptTyp(String value) {
        this.otptTyp = value;
    }

    /**
     * Gets the value of the otptNme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtptNme() {
        return otptNme;
    }

    /**
     * Sets the value of the otptNme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtptNme(String value) {
        this.otptNme = value;
    }

    /**
     * Gets the value of the publDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublDir() {
        return publDir;
    }

    /**
     * Sets the value of the publDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublDir(String value) {
        this.publDir = value;
    }

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the usrNme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrNme() {
        return usrNme;
    }

    /**
     * Sets the value of the usrNme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrNme(String value) {
        this.usrNme = value;
    }

    /**
     * Gets the value of the inptData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inptData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInptData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.w3._2005._05.xmlmime.Base64Binary }
     * 
     * 
     */
    public List<Base64Binary> getInptData() {
        if (inptData == null) {
            inptData = new ArrayList<Base64Binary>();
        }
        return this.inptData;
    }

}
