//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 02:27:23 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://csf.com/DocumentGeneratorService/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.csf.documentgeneratorservice;
