//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 02:27:23 PM CEST 
//


package org.datacontract.schemas._2004._07.realtimeserver;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RenderData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RenderData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PageCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SheetCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanionFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanionData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reserved1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reserved2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reserved3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reserved4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RenderData", propOrder = {
    "name",
    "path",
    "dataType",
    "pageCount",
    "data",
    "sheetCount",
    "companionFile",
    "companionData",
    "reserved1",
    "reserved2",
    "reserved3",
    "reserved4"
})
public class RenderData {

    @XmlElementRef(name = "Name", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> name;
    @XmlElementRef(name = "Path", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> path;
    @XmlElementRef(name = "DataType", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> dataType;
    @XmlElementRef(name = "PageCount", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> pageCount;
    @XmlElementRef(name = "Data", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> data;
    @XmlElementRef(name = "SheetCount", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> sheetCount;
    @XmlElementRef(name = "CompanionFile", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> companionFile;
    @XmlElementRef(name = "CompanionData", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> companionData;
    @XmlElementRef(name = "Reserved1", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> reserved1;
    @XmlElementRef(name = "Reserved2", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> reserved2;
    @XmlElementRef(name = "Reserved3", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> reserved3;
    @XmlElementRef(name = "Reserved4", namespace = "http://schemas.datacontract.org/2004/07/RealTimeServer", type = JAXBElement.class)
    protected JAXBElement<String> reserved4;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPath(JAXBElement<String> value) {
        this.path = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDataType(JAXBElement<String> value) {
        this.dataType = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the pageCount property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPageCount() {
        return pageCount;
    }

    /**
     * Sets the value of the pageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPageCount(JAXBElement<String> value) {
        this.pageCount = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setData(JAXBElement<String> value) {
        this.data = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the sheetCount property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSheetCount() {
        return sheetCount;
    }

    /**
     * Sets the value of the sheetCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSheetCount(JAXBElement<String> value) {
        this.sheetCount = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the companionFile property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCompanionFile() {
        return companionFile;
    }

    /**
     * Sets the value of the companionFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCompanionFile(JAXBElement<String> value) {
        this.companionFile = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the companionData property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCompanionData() {
        return companionData;
    }

    /**
     * Sets the value of the companionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCompanionData(JAXBElement<String> value) {
        this.companionData = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the reserved1 property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReserved1() {
        return reserved1;
    }

    /**
     * Sets the value of the reserved1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReserved1(JAXBElement<String> value) {
        this.reserved1 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the reserved2 property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReserved2() {
        return reserved2;
    }

    /**
     * Sets the value of the reserved2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReserved2(JAXBElement<String> value) {
        this.reserved2 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the reserved3 property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReserved3() {
        return reserved3;
    }

    /**
     * Sets the value of the reserved3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReserved3(JAXBElement<String> value) {
        this.reserved3 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the reserved4 property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReserved4() {
        return reserved4;
    }

    /**
     * Sets the value of the reserved4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReserved4(JAXBElement<String> value) {
        this.reserved4 = ((JAXBElement<String> ) value);
    }

}
