//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 02:27:23 PM CEST 
//


package com.csf.documentgeneratorservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;

import org.datacontract.schemas._2004._07.realtimeserver.RenderData;
import org.w3._2005._05.xmlmime.Base64Binary;


/**
 * <p>Java class for tDocumentGenerationResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDocumentGenerationResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrCde" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ErrMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MsgId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GenDoc" type="{http://www.w3.org/2005/05/xmlmime}base64Binary" minOccurs="0"/>
 *         &lt;element name="DocStreamArray" type="{http://schemas.datacontract.org/2004/07/RealTimeServer}RenderData" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenerateDocumentResponse", propOrder = {
    "errCde",
    "errMsg",
    "msgId",
    "genDoc",
    "docStreamArray"
})
@XmlRootElement(name = "GenerateDocumentResponse",namespace = "http://csf.com/DocumentGeneratorService/")
public class DocumentGenerationResponse {

    @XmlElement(name = "ErrCde")
    protected int errCde;
    @XmlElement(name = "ErrMsg")
    protected String errMsg;
    @XmlElement(name = "MsgId")
    protected String msgId;
    @XmlElement(name = "GenDoc")
    protected Base64Binary genDoc;
    @XmlElement(name = "DocStreamArray", required = true)
    protected List<RenderData> docStreamArray;

    /**
     * Gets the value of the errCde property.
     * 
     */
    public int getErrCde() {
        return errCde;
    }

    /**
     * Sets the value of the errCde property.
     * 
     */
    public void setErrCde(int value) {
        this.errCde = value;
    }

    /**
     * Gets the value of the errMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * Sets the value of the errMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrMsg(String value) {
        this.errMsg = value;
    }

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the genDoc property.
     * 
     * @return
     *     possible object is
     *     {@link org.w3._2005._05.xmlmime.Base64Binary }
     *     
     */
    public Base64Binary getGenDoc() {
        return genDoc;
    }

    /**
     * Sets the value of the genDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.w3._2005._05.xmlmime.Base64Binary }
     *     
     */
    public void setGenDoc(Base64Binary value) {
        this.genDoc = value;
    }

    /**
     * Gets the value of the docStreamArray property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docStreamArray property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocStreamArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.datacontract.schemas._2004._07.realtimeserver.RenderData }
     * 
     * 
     */
    public List<RenderData> getDocStreamArray() {
        if (docStreamArray == null) {
            docStreamArray = new ArrayList<RenderData>();
        }
        return this.docStreamArray;
    }

}
